### ISSUE TITLE
C-# for inline documentation raises an error message: "Wrong type argument: hash-table-p, []"

### ISSUE THREAD

**Issue by parvizfarnia** [brotzeit/rustic#212] opened 2021-01-09 13:01 UTC
Hello everyone

I've encountered a somewhat strange issue with inline documentation (Org files) in Emacs using rustic module.

My environment:
```
OS: Ubuntu 20.04 (x86_64)
Emacs version: 27.1
Most recent version of Rustic and LSP installed from MELPA
Pandoc version: 2.11
```

In order to convert the documentation of the standard library I proceeded as indicated in the guide:

- I run `M-x rustic-doc-mode` to enable the doc-mode
- Then I run `M-x rustic-doc-setup`

It took several minutes and the job was done. By pressing `C-#` followed by a searched `key word` I can view a very nice formatted documentation with beautiful syntax highlighting. Everything works great. But everythnig works great until the Emacs is open. As soon as close Emacs and I open it later, after enabling rustic-doc-mode in an open Rustic buffer, any attempt of `C-#` to search any documentation will result the following error messages:

- The error message that I can see in Emacs Message bar:
`Wrong type argument: hash-table-p, []`

- The error message that I can see in Emacs `*Message*` buffer:
`rustic-doc--thing-at-point: Wrong type argument: hash-table-p, []`

- And also an error message in `*rls::stderr*` buffer (but I unlike the two above-mentioned error messages I don't get this error message in this buffer every time and I don't know why)
```
[2021-01-08T19:21:33Z ERROR rls::actions] failed to fetch project model, using fallback: failed to read `/home/myuser
/Documents/Rust/progs/testapp/src/Cargo.toml

```

The only solution that I've found so far, is to repeat the whole process of converting the standard library documentation as indicated in the Github guide, which of course solves the problem but obviously doesn't make sense for a regular use. I thought maybe my rustic and LSP installation was somewhat broken so I removed these packages manually and completely from my `~/.emacs.d/elpa` directory and then I reinstalled them via MELPA (`M-x install-package [RET] . . . [RET]`). But even doing this didn't solve the problem.

So I was wondering whether anyone has encountered the same issue.

Thanks in advance

**Comment by brotzeit** [comment] 2021-01-09 13:34
@samhedin can you help me out.

**Comment by samhedin** [comment] 2021-01-09 20:32
I can not reproduce this. Initially, I thought that it was because you seem to be using RLS and I've only tried it with rust-analyzer, but after giving it a go with RLS it seems just fine.

Do you have any more details of what's going on? And if you can, please try with rust-analyzer and see if it works there. (It should work with both RLS and RA of course, but at least we'll know where to look)

**Comment by parvizfarnia** [comment] 2021-01-10 14:12
Thank you very much both of you for your attention to my problem.


I followed what @samhedin suggested, that is, using rust-analyzer instead of RLS, so here is how I proceeded:

- Downloading the most recent version of rust-analyzer:
`wget https://github.com/rust-analyzer/rust-analyzer/releases/download/2021-01-04/rust-analyzer-linux`

- Renaming it:
`mv rust-analyzer-linux rust-analyzer`

- Make it executable:
`chmod u+x rust-analyzer`

- And finally add it to the `bin` direrctory of Cargo:
`mv rust-analyzer "${CARGO_HOME}"/bin`

- Then I put the following line in comment in my emacs init file

`;;  (setq rustic-lsp-server 'rls)`

And instead I added the follwoing:

`(setq lsp-rust-analyzer-server-command '("${CARGO_HOME}/bin/rust-analyzer"))`

I closed Emacs and I opened it again. Then I opened a Rustic buffer in which I enabled rustic-doc `(M-x rustic-doc-mode)`. After that the problem was solved and once again I was able to search the documentation via `C-# Keyword`. I closed/opened Emacs several times and each time I repeated theses steps just to make sure that there was no more issue. So it seems that by using rust-analyzer instead of rls the problem is solved.

However by using this method when I open a Rust program, here is what I see in Emacs status bar at the bottom of the window:

`-:--- main.rs        All (1,0)        (Rustic LSP[rust-analyzer:3284]   FlyC   WS  ivy  WK)`


Which seems to me normal, but at the same time there is an error message in Emacs message bar:

`LSP : Error from Language Server: Rust Analyzer is still loading... (Unknown error)`

And no matter how long I wait, this message remains in Emacs message bar until I start typing. Only then this error message disapears and everything including the inline documentation works normally. 

In the case where it might be helpful for analyzing this error message, here are the contents of several buffers in my Emacs when rust-analyzer is loaded:


```*Message* buffer content : ```
===================
```
Loading /home/myuser/.emacs.d/myinit.el (source)...
[yas] Prepared just-in-time loading of snippets successfully.
Loading /home/myuser/.emacs.d/my_scripts/font-lock+.el (source)...
Loading font-lock...done
Loading /home/myuser/.emacs.d/my_scripts/font-lock+.el (source)...done
Waiting for git... [2 times]
[yas] Prepared just-in-time loading of snippets successfully.
Loading /home/myuser/.emacs.d/myinit.el (source)...done
Loaded /home/myuser/.emacs.d/myinit.el
For information about GNU Emacs and the GNU system, type C-h C-a.
Package cl is deprecated
LSP :: Connected to [rust-analyzer:3463 status:starting].
LSP :: rust-analyzer:3463 initialized successfully
LSP :: Error from the Language Server: Rust Analyzer is still loading... (Unknown error) [6 times]
Rustic-Doc mode enabled in current buffer
```

```*lsp-log* buffer content:```
===================
```
Command "rls" is present on the path.
Command "/usr/local/rust/cargo/bin/rust-analyzer" is present on the path.
Command "rls" is present on the path.
Command "/usr/local/rust/cargo/bin/rust-analyzer" is present on the path.
Found the following clients for /home/myuser/Documents/Rust/progs/testapp/src/main.rs: (server-id rls, priority -1), (server-id rust-analyzer, priority 1)
The following clients were selected based on priority: (server-id rust-analyzer, priority 1)
Creating watch for /home/myuser/Documents/Rust/progs/testapp/src
```


```*rust-analyzer* buffer content:```
=======================
It's empty



```*rust-analyzer::stderr* buffer content:```
===========================
It's also empty



Based on the above mentioned contents, I don't see anything unusal (please correct me if I'm wrong) so I wonder 
whether the LSP error message is really an issue or simply a buffer refreshing problem in Emacs. 


But I confirm the main issue is resolved, that is, **using rust-analyzer instead of rls** allows to view inline 
documentation in Emacs and it works normally.


Should I close the issue now?

**Comment by samhedin** [comment] 2021-01-10 19:14
Thanks for giving it a go!
Well, the issue isn't entirely resolved. As far as I remember, RLS is the officially recommended language server. However, it seems that when you actually ask people, they tend to use and recommend RA. One day RA will become the officially sanctioned server but that might still be some way off. 
On principle, I think `rustic-doc` should work with both, but if it's a massive undertaking (it probably isn't) then maybe there are more important things. I'll take a look, so let this be open for now.

As far as the `RA is still loading` message goes, I have noticed it too, but that's probably for another issue :)

**Comment by brotzeit** [comment] 2021-01-10 19:46
AFAIK rust-analyzer is the de-facto standard for some time.

**Comment by samhedin** [comment] 2021-01-10 21:25
In that case, I will close this. We can re-open if more people want it to work with RLS.

**Closed by samhedin** 2021-01-10 21:25 UTC
Labels: rustdoc
