### ISSUE TITLE
Find definition

### ISSUE THREAD

**Issue by rakanalh** [brotzeit/rustic#62] opened 2019-09-18 22:42 UTC
Hello,

I was able to install and use rusic without issues generally except for one. rustic does not provide jumping to function definition and using `lsp-find-definition` results in:
```
lsp-goto-type-definition: Capability not supported by the language server: "typeDefinitionProvider"
```

Is there an alternative that is currently not documented?

**Comment by brotzeit** [comment] 2019-09-19 05:43
When I started writing this package, `lsp-mode` and `eglot` both used `xref` facilities for this stuff. I'm not sure if `lsp-find-definition` is the prefered way now. I will take a look at both packages and document it here.

`xref-find-definitions` should work.

**Comment by rakanalh** [comment] 2019-09-19 07:24
Hi @brotzeit,

I also tried `xref-find-definition` before i wrote this issue and it was asking for the "TAGS" file and i thought that it shouldn't be the case.

**Comment by brotzeit** [comment] 2019-09-19 07:49
Ok, then please pull the latest changes and run `list-processes`. Do you see your lsp process ?

**Comment by rakanalh** [comment] 2019-09-19 08:14
I have the latest version from yesterday. Yes, seems like the LSP process is working 
![DeepinScreenshot_select-area_20190919101349](https://user-images.githubusercontent.com/195829/65225906-3dfecf80-dac6-11e9-8a88-c572724ac122.png)

**Comment by rakanalh** [comment] 2019-09-19 08:25
Seems like i had rust mode installed which was somehow interfering with rustic. I cleaned up my rust configs and now i only have `(use-package rustic)`. Other packages have been removed.

I see the following error:

```
rustic-setup-rls: Symbol’s function definition is void: lsp-workspace-folders-add
```

**Comment by brotzeit** [comment] 2019-09-19 08:30
Ok I can reproduce it. The reason is that lsp-mode isn't required before rust.
However I implemented that rustic requires lsp-mode automatically. This doesn't seem to work anymore. I have to take a look at it.

**Comment by brotzeit** [comment] 2019-09-19 12:03
I merged a PR without properly reviewing it half a year ago. I will push the fix today.

**Comment by brotzeit** [comment] 2019-09-19 12:18
Can you please test the latest change Without lsp-mode required.

**Closed** 2019-09-20 06:52 UTC
Labels: bug

**Comment by brotzeit** [comment] 2019-09-20 08:15
You're welcome. However it shouldn't be necessary to add rustic to auto-mode-alist and require lsp-mode before rustic. I have added some stuff to simplify the setup for users(if it doesn't work without it would be nice if you tell me). You maybe also want to set your bindings in `prog-mode-map`, if you use emacs for other languages than rust.
